// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOGtAAu_lRxQjjrgScDc2oFuwYiX0Bdng',
    appId: '1:901844026975:web:aba795dac1cdd764b13dea',
    messagingSenderId: '901844026975',
    projectId: 'attendance-app-28d8b',
    authDomain: 'attendance-app-28d8b.firebaseapp.com',
    storageBucket: 'attendance-app-28d8b.firebasestorage.app',
    measurementId: 'G-2S0H1MW9PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq8IChUju1pLMiS3pI2YCuUzGC2mDMVyk',
    appId: '1:901844026975:android:6a25f8760c66be03b13dea',
    messagingSenderId: '901844026975',
    projectId: 'attendance-app-28d8b',
    storageBucket: 'attendance-app-28d8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8AxbpEtN1xO64G0iD55p78yggDibEFY',
    appId: '1:901844026975:ios:94728e7d6c968952b13dea',
    messagingSenderId: '901844026975',
    projectId: 'attendance-app-28d8b',
    storageBucket: 'attendance-app-28d8b.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT8AxbpEtN1xO64G0iD55p78yggDibEFY',
    appId: '1:901844026975:ios:94728e7d6c968952b13dea',
    messagingSenderId: '901844026975',
    projectId: 'attendance-app-28d8b',
    storageBucket: 'attendance-app-28d8b.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOGtAAu_lRxQjjrgScDc2oFuwYiX0Bdng',
    appId: '1:901844026975:web:fbf20a1abe984ad0b13dea',
    messagingSenderId: '901844026975',
    projectId: 'attendance-app-28d8b',
    authDomain: 'attendance-app-28d8b.firebaseapp.com',
    storageBucket: 'attendance-app-28d8b.firebasestorage.app',
    measurementId: 'G-GBTNK7M7GT',
  );
}
